### ISSUE TITLE
/bin/bash:1269: nix: command not found

### ISSUE THREAD

**Issue by moorthi07** [superherointj/nix-auto-gpt#12]
on mac
~ % cd AutoGPT 
direnv: error /Users/xx/AutoGPT/.envrc is blocked. Run `direnv allow` to approve its content

when run  `direnv allow`

 % direnv allow

direnv: loading ~/space/AutoGPT/.envrc                                                                                    
direnv: using flake github:superherointj/nix-auto-gpt
**/bin/bash:1269: nix: command not found**

**Comment by superherointj** [comment]
You need to have `nix` package manager installed.

https://nixos.org/download
