### ISSUE TITLE
`autogpt` module not found when using `direnv`

### ISSUE THREAD

**Issue by drupol** [superherointj/nix-auto-gpt#9]
Hello,

When loading the development environment with `direnv`, the `autogpt` module is not found:

![image](https://user-images.githubusercontent.com/252042/236624851-d7d48c7c-0abe-4c35-8ff1-45be446d4a01.png)

**Comment by superherointj** [comment]
This repository is only the Nix files. Try to clone AutoGPT repository instead. And run command from there.

`direnv` will automatically load Nix packages from here in that repository.

(that sort of explains why `.envrc` was missing here)

Context: https://github.com/Significant-Gravitas/Auto-GPT/blob/master/.envrc

**Comment by drupol** [comment]
Fair enough ! Understood.

The issue is that now the `distro` module is not found.

After that, same with `auto_gpt_plugin_template`

**Comment by superherointj** [comment]
It's hard to keep up with changes in Auto-GPT. It's also being re-written atm.
I'm currently porting all missing python packages to a [discrete repository](https://github.com/nixpkgs-friendly/nixpkgs-friendly-overlay) (that is not nixpkgs, because review process in nixpkgs is tricky).
Feel free to suggest any fix/improvement.

**Comment by drupol** [comment]
Oh ok, so then this is currently broken.

I added `distro` since it is available in Nix, but `auto_gpt_plugin_template` is not.
I provided the package manually:

<details>

```nix
{ fetchPypi
, lib
, python3
}:

python3.pkgs.buildPythonPackage rec {
  pname = "auto_gpt_plugin_template";
  version = "0.0.3";
  format = "pyproject";

  src = fetchPypi {
    inherit pname version;
    sha256 = "sha256-P1ERD3jbSQqJpRQvzfRBdu8IgSWkGPUHsQDoE+pa/QY=";
  };

  nativeBuildInputs = with python3.pkgs; [
    hatchling
  ];

  doCheck = false;
}
```
</details>
 but it fails at some point:

```
$ direnv reload
direnv: loading ~/Code/superherointj/nix-auto-gpt/.envrc
direnv: using flake
error: builder for '/nix/store/y92wn4fiknmclxiayzj2m1vjixhpa52p-python3.10-auto_gpt_plugin_template-0.0.3.drv' failed with exit code 1;
       last 25 log lines:
       > patching sources
       > configuring
       > no configure script, doing nothing
       > building
       > Executing pipBuildPhase
       > Creating a wheel...
       > WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
       > Processing /build/auto_gpt_plugin_template-0.0.3
       >   Running command Preparing metadata (pyproject.toml)
       >   Preparing metadata (pyproject.toml) ... done
       > Building wheels for collected packages: auto_gpt_plugin_template
       >   Running command Building wheel for auto_gpt_plugin_template (pyproject.toml)
       >   Building wheel for auto_gpt_plugin_template (pyproject.toml) ... done
       >   Created wheel for auto_gpt_plugin_template: filename=auto_gpt_plugin_template-0.0.3-py3-none-any.whl size=3382 sha256=b700c64f1863d3e93b1388520010bc2cdc2f91cffa1a04495cf24db3a32c581f
       >   Stored in directory: /build/pip-ephem-wheel-cache-d9ruk88m/wheels/f4/94/af/352bc1dfa8baaaca5add8daa1d46093635aaed328fe566aacc
       > Successfully built auto_gpt_plugin_template
       > Finished creating a wheel...
       > Finished executing pipBuildPhase
       > installing
       > Executing pipInstallPhase
       > /build/auto_gpt_plugin_template-0.0.3/dist /build/auto_gpt_plugin_template-0.0.3
       > Processing ./auto_gpt_plugin_template-0.0.3-py3-none-any.whl
       > ERROR: Could not find a version that satisfies the requirement abstract-singleton (from auto-gpt-plugin-template) (from versions: none)
       > ERROR: No matching distribution found for abstract-singleton
       > 
       For full logs, run 'nix log /nix/store/y92wn4fiknmclxiayzj2m1vjixhpa52p-python3.10-auto_gpt_plugin_template-0.0.3.drv'.
error: 1 dependencies of derivation '/nix/store/h72y8rd9wkv17j9g1hqzh87lai1c0anl-python3-3.10.10-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d2zai1dq1d9m2iax6zj98g5yrzgjaf0n-nix-shell-env.drv' failed to build
error: getting status of '/home/pol/Code/superherointj/nix-auto-gpt/.direnv/flake-profile.1093619': No such file or directory
direnv: nix-direnv: renewed cache
direnv: export ~XDG_DATA_DIRS
```

**Comment by superherointj** [comment]
Then [abstract-singleton](https://pypi.org/project/abstract-singleton/) is also missing. Also missing from nixpkgs.

[I'm currently working on adding the missing packages to the discrete repo.]

**Comment by drupol** [comment]
I finally got everything working in my fork, feel free to pick the files at: https://github.com/drupol/nix-auto-gpt

![image](https://user-images.githubusercontent.com/252042/236627638-df0bc673-a17e-4786-99a7-6a5e3b45a39e.png)

**Comment by superherointj** [comment]
Auto-GPT upstream is already referencing this repository. So would be best to integrate fixes here. Can you propose a PR? [It's also good because it keeps credit.]

Ideally python packages should be upstreamed to nixpkgs.
